### ISSUE TITLE
about the train

### ISSUE THREAD

**Issue by thousanddrowned** [LIA-DiTella/nsdf_editing#4]
Good works! I have some issues about your train, in your code ,every train only read one file? I wonder if  I'm right.

**Comment by miguef98** [comment]
Thanks for the question!
You are correct, the train.py file performs the overfitting on only one shape. If you want to train multiple files, take a look at the "cuantitative.py" file. This is the script we used for the experiments of the paper, which also computes metrics (Chamfer distance and normal alignment).
Hope that helps!

**Comment by thousanddrowned** [comment]
OK,thanks
